/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MIB.Inloggning.Sidor;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Hampus
 */
public class VisaAllInfoAlien extends javax.swing.JPanel {
    private InfDB idb;

    /**
     * Creates new form VisaAllInfoAlien
     */
    public VisaAllInfoAlien(InfDB databas) {
        idb = databas;
        initComponents();
        sattVardeCbValjRas();
    }
    
    private void sattVardeCbValjRas(){
    
    cbAlienRas.addItem("Ingen ras");
    cbAlienRas.addItem("Boglodite");
    cbAlienRas.addItem("Squid");
    cbAlienRas.addItem("Worm");
    
    }
    
private void sattVardeCbValjIndivid(){
    
    cbAlienIndivid.removeAllItems();
    
    String valdRas = cbAlienRas.getSelectedItem().toString();
    
    try{
        
        if(valdRas.equals("Boglodite")) {
            
            String fragaBoglodite = "select alien.NAMN from alien join boglodite on boglodite.ALIEN_ID = alien.ALIEN_ID";

            ArrayList<String> boglodite;
             
            boglodite = idb.fetchColumn(fragaBoglodite);
            
        for(String bogloditeNamn : boglodite) {
            cbAlienIndivid.addItem(bogloditeNamn);
        }
        
        } else if(valdRas.equals("Squid")) {
            
            String fragaSquid = "select alien.NAMN from alien join squid on squid.ALIEN_ID = alien.ALIEN_ID";
            
            ArrayList<String> squid;
             
            squid = idb.fetchColumn(fragaSquid);
            
        for(String squidNamn : squid) {
            cbAlienIndivid.addItem(squidNamn);
        }
    
    
        } else if(valdRas.equals("Worm")) {
            
            String fragaWorm = "select alien.NAMN from alien join worm on worm.ALIEN_ID = alien.ALIEN_ID";
            
            ArrayList<String> worm;
             
            worm = idb.fetchColumn(fragaWorm);
            
        for(String wormNamn : worm) {
            cbAlienIndivid.addItem(wormNamn);
        }
        
        }
    } catch (InfException e) {
        JOptionPane.showMessageDialog(null, "InfException");
        
    } catch (NullPointerException e){
        JOptionPane.showMessageDialog(null, "null-fel igen");
    }
    
}

private void printInfo(){
    
    taVisaAlienInfo.setText("");
    
    HashMap<String, String> hamtaInfo = new HashMap<String,String>();
    
    try{
        
        String valdIndivid = cbAlienIndivid.getSelectedItem().toString();
        String sqlFraga = "select alien.NAMN, alien.REGISTRERINGSDATUM, alien.TELEFON, omrade.BENAMNING from alien join omrade on omrade.OMRADES_ID = alien.PLATS where alien.NAMN = '" + valdIndivid + "'";
        hamtaInfo = idb.fetchRow(sqlFraga);
        
        taVisaAlienInfo.append(hamtaInfo.get("NAMN") + "\t");
        taVisaAlienInfo.append(hamtaInfo.get("REGISTRERINGSDATUM") + "\t");
        taVisaAlienInfo.append(hamtaInfo.get("TELEFON") + "\t");
        taVisaAlienInfo.append(hamtaInfo.get("BENAMNING") + "\n");
    
    } catch(InfException e) {
        JOptionPane.showMessageDialog(null, "InfException");
    } catch (NullPointerException e) {
        
    }
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbAlienIndivid = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        taVisaAlienInfo = new javax.swing.JTextArea();
        cbAlienRas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setText("Visa all information om en alien");

        jLabel1.setText("Välj ras:");

        cbAlienIndivid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlienIndividActionPerformed(evt);
            }
        });

        taVisaAlienInfo.setColumns(20);
        taVisaAlienInfo.setRows(5);
        jScrollPane1.setViewportView(taVisaAlienInfo);

        cbAlienRas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlienRasActionPerformed(evt);
            }
        });

        jLabel2.setText("Välj individ:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(cbAlienRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbAlienIndivid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAlienRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAlienIndivid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbAlienRasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlienRasActionPerformed
        // TODO add your handling code here:
        sattVardeCbValjIndivid();
        
    }//GEN-LAST:event_cbAlienRasActionPerformed

    private void cbAlienIndividActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlienIndividActionPerformed
        // TODO add your handling code here:
        printInfo();
    }//GEN-LAST:event_cbAlienIndividActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbAlienIndivid;
    private javax.swing.JComboBox<String> cbAlienRas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taVisaAlienInfo;
    // End of variables declaration//GEN-END:variables
}
