/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MIB.Inloggning.Sidor;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Hampus
 */
public class VisaChefForValtOmrade extends javax.swing.JPanel {
    private InfDB idb;

    /**
     * Creates new form VisaChefForValtOmrade
     * @param databas
     */
    public VisaChefForValtOmrade(InfDB databas) {
        idb = databas;
        initComponents();
        sattVardeComboBox();
    }
    
    private void sattVardeComboBox(){
        
        String sqlF = "select omrades_id from omrade;";
        
        try{
        
             ArrayList<String> omraden;
             
             omraden = idb.fetchColumn(sqlF);
            
        for(String benamning : omraden) {
            cbValjChefOmrade.addItem(benamning);
        }
        
    }
        catch(InfException e){
        JOptionPane.showMessageDialog(null, "Databas felar");
        }
        
        catch(Exception undantag){
        //JOptionPane.showMessageDialog(null, "Något annat felar");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbValjChefOmrade = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        taVisInfoChefOmrade = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        cbValjChefOmrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbValjChefOmradeActionPerformed(evt);
            }
        });

        taVisInfoChefOmrade.setColumns(20);
        taVisInfoChefOmrade.setRows(5);
        jScrollPane1.setViewportView(taVisInfoChefOmrade);

        jLabel1.setText("Välj område att visa agent för:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(cbValjChefOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbValjChefOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbValjChefOmradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbValjChefOmradeActionPerformed
        // TODO add your handling code here:
        taVisInfoChefOmrade.setText("");
        
        HashMap<String, String> sokAgent = new HashMap<String,String>();
        
        try{
        
        String omrade_id = cbValjChefOmrade.getSelectedItem().toString();
        String fraga = "select agent.AGENT_ID, agent.NAMN, agent.TELEFON, agent.OMRADE from AGENT where omrade = '" + omrade_id + "'"; 
        sokAgent = idb.fetchRow(fraga);
            
                taVisInfoChefOmrade.append(sokAgent.get("OMRADE") + "\t");
                taVisInfoChefOmrade.append(sokAgent.get("NAMN") + "\t");
                taVisInfoChefOmrade.append(sokAgent.get("TELEFON") + "\t");
               
            
        }
        catch(InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
        }
        catch(IndexOutOfBoundsException e) {
             JOptionPane.showMessageDialog(null, "Något gick fel");
        }
    }//GEN-LAST:event_cbValjChefOmradeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbValjChefOmrade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taVisInfoChefOmrade;
    // End of variables declaration//GEN-END:variables
}
