/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MIB.Inloggning.Sidor;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Hampus
 */
public class VisaAlienOmrade extends javax.swing.JPanel {
    private InfDB idb;

    /**
     * Creates new form VisaAlienOmrade
     */
    public VisaAlienOmrade(InfDB databas) {
        idb = databas;
        initComponents();
        sattVardeComboBox();
        
    }
    
    private void sattVardeComboBox(){
        
        String sqlF = "select omrades_id from omrade;";
     
        try{
        
             ArrayList<String> omraden;
             
             omraden = idb.fetchColumn(sqlF);
            
        for(String benamning : omraden) {
            cbValjOmrade.addItem(benamning);
            }
        
    }
        catch(InfException e){
        JOptionPane.showMessageDialog(null, "Databas felar");
        }
        
        catch(Exception undantag){
        //JOptionPane.showMessageDialog(null, "Något annat felar");
        }
        
    }
    
    private void skrivUtInfo(){
        
    taVisaAlienInfo.setText("");
       
              ArrayList<HashMap<String, String>> sokAlien = new ArrayList<>();
              
        try{
        
        String omrades_id = cbValjOmrade.getSelectedItem().toString();
      
        String fraga = "select alien.NAMN, alien.TELEFON, omrade.BENAMNING from alien join omrade on alien.PLATS = omrade.OMRADES_ID where omrades_id = '" + omrades_id + "'"; 
        sokAlien = idb.fetchRows(fraga);
        
        for(HashMap<String, String> alien : sokAlien) {

                taVisaAlienInfo.append(alien.get("NAMN") + "\t");
                taVisaAlienInfo.append(alien.get("TELEFON") + "\t");
                taVisaAlienInfo.append(alien.get("BENAMNING") + "\n");
            
        }
        }
        catch(InfException e) {
             JOptionPane.showMessageDialog(null, "Databasfel");
        }
        catch(IndexOutOfBoundsException e) {
             JOptionPane.showMessageDialog(null, "Något gick fel");
        }
        catch(NullPointerException e) {
            JOptionPane.showMessageDialog(null, "null-fel");
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbValjOmrade = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        taVisaAlienInfo = new javax.swing.JTextArea();

        jLabel1.setText("Lista alla aliens på plats");

        jLabel2.setText("Välj område:");

        cbValjOmrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbValjOmradeActionPerformed(evt);
            }
        });

        taVisaAlienInfo.setColumns(20);
        taVisaAlienInfo.setRows(5);
        jScrollPane1.setViewportView(taVisaAlienInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbValjOmrade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbValjOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbValjOmradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbValjOmradeActionPerformed
        // TODO add your handling code here:
        skrivUtInfo();
    }//GEN-LAST:event_cbValjOmradeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbValjOmrade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taVisaAlienInfo;
    // End of variables declaration//GEN-END:variables
}
