/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MIB;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Hampus
 */
public class JFGeAgentAdmin extends javax.swing.JFrame {
    private InfDB idb;
    //JFGeAgentAdmin geAdmin;

    /**
     * Creates new form JFGeAgentAdmin
     */
    public JFGeAgentAdmin(InfDB databas) {
        initComponents();
        idb = databas;
        //geAdmin = new JFGeAgentAdmin(idb);
        sattVardePaComboBox();
    }
    
    private void sattVardePaComboBox(){
    
        try{
        ArrayList<String> namnAgenter = new ArrayList<String>();
        
        String sqlFraga = "select namn from agent where administrator = 'N'";
        
        namnAgenter = idb.fetchColumn(sqlFraga);
        
        for(String namn : namnAgenter) {
            cbValjAgent.addItem(namn);
        }
        
        }
        catch (InfException e) {
        
        }
    }
        
        private void sparaIDatabas(){
        
            String valdAgent = cbValjAgent.getSelectedItem().toString();
            
        try {
                  
            idb.update("update agent set administrator = 'J' where namn = '" + valdAgent + "'");

        } catch (InfException ex) {
            
        }
        // Berätta att det är sparat och stäng fönster
        //geAdmin.setVisible(false);
        JOptionPane.showMessageDialog(null, "Adminstatus tillagd");
                        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbValjAgent = new javax.swing.JComboBox<>();
        jbSpara = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbSpara.setText("Spara");
        jbSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSparaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSpara, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbValjAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(cbValjAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jbSpara)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSparaActionPerformed
        // TODO add your handling code here:
        sparaIDatabas();
    }//GEN-LAST:event_jbSparaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbValjAgent;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbSpara;
    // End of variables declaration//GEN-END:variables
}
