/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MIB;

import MIB.Inloggning.Sidor.RegistreraAliens;
import MIB.Inloggning.Sidor.RegistreraUtrustning;
import java.awt.BorderLayout;
import oru.inf.InfDB;

/**
 *
 * @author Hampus
 */
public class JFRegistreraUtrustning extends javax.swing.JFrame {
    private static InfDB idb;
    RegistreraUtrustning regUtrustning;

    /**
     * Creates new form JFRegistreraUtrustning
     */
    public JFRegistreraUtrustning() {
        //idb = databas;
        initComponents();
        regUtrustning = new RegistreraUtrustning();
        pnlRegistreraUtrustning.setLayout(new BorderLayout());
        pnlRegistreraUtrustning.add(regUtrustning);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistreraUtrustning = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout pnlRegistreraUtrustningLayout = new javax.swing.GroupLayout(pnlRegistreraUtrustning);
        pnlRegistreraUtrustning.setLayout(pnlRegistreraUtrustningLayout);
        pnlRegistreraUtrustningLayout.setHorizontalGroup(
            pnlRegistreraUtrustningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlRegistreraUtrustningLayout.setVerticalGroup(
            pnlRegistreraUtrustningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistreraUtrustning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistreraUtrustning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlRegistreraUtrustning;
    // End of variables declaration//GEN-END:variables
}
