/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MIB;

import MIB.Inloggning.Sidor.VisaAlienRas;
import MIB.Inloggning.Sidor.VisaAllInfoAlien;
import java.awt.BorderLayout;
import oru.inf.InfDB;

/**
 *
 * @author Hampus
 */
public class JFVisaAllInfoAlien extends javax.swing.JFrame {
    private static InfDB idb;
    VisaAllInfoAlien visaAllInfoAlien;

    /**
     * Creates new form JFVisaAllInfoAlien
     */
    public JFVisaAllInfoAlien(InfDB databas) {
        idb = databas;
        initComponents();
        visaAllInfoAlien = new VisaAllInfoAlien(idb);
        pnlVIsaAllInfoAlien.setLayout(new BorderLayout());
        pnlVIsaAllInfoAlien.add(visaAllInfoAlien);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVIsaAllInfoAlien = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout pnlVIsaAllInfoAlienLayout = new javax.swing.GroupLayout(pnlVIsaAllInfoAlien);
        pnlVIsaAllInfoAlien.setLayout(pnlVIsaAllInfoAlienLayout);
        pnlVIsaAllInfoAlienLayout.setHorizontalGroup(
            pnlVIsaAllInfoAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlVIsaAllInfoAlienLayout.setVerticalGroup(
            pnlVIsaAllInfoAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVIsaAllInfoAlien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVIsaAllInfoAlien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlVIsaAllInfoAlien;
    // End of variables declaration//GEN-END:variables
}
