/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MIB;

import MIB.Inloggning.Sidor.SokAliensMellanDatum;
import MIB.Inloggning.Sidor.VisaAlienOmrade;
import java.awt.BorderLayout;
import oru.inf.InfDB;

/**
 *
 * @author Hampus
 */
public class JFVisaAlienOmrade extends javax.swing.JFrame {
    private static InfDB idb;
    VisaAlienOmrade visaAlienOmrade;

    /**
     * Creates new form JFVisaAlienOmrade
     */
    public JFVisaAlienOmrade(InfDB datbas) {
        idb = datbas;
        initComponents();
        visaAlienOmrade = new VisaAlienOmrade(idb);
        pnlVisaAlienOmrade.setLayout(new BorderLayout());
        pnlVisaAlienOmrade.add(visaAlienOmrade);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVisaAlienOmrade = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout pnlVisaAlienOmradeLayout = new javax.swing.GroupLayout(pnlVisaAlienOmrade);
        pnlVisaAlienOmrade.setLayout(pnlVisaAlienOmradeLayout);
        pnlVisaAlienOmradeLayout.setHorizontalGroup(
            pnlVisaAlienOmradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlVisaAlienOmradeLayout.setVerticalGroup(
            pnlVisaAlienOmradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVisaAlienOmrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVisaAlienOmrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlVisaAlienOmrade;
    // End of variables declaration//GEN-END:variables
}
