/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MIB;

import MIB.Inloggning.MenyAdmin;
import java.awt.BorderLayout;
import oru.inf.InfDB;

/**
 *
 * @author Hampus
 */
public class MainFrameAdmin extends javax.swing.JFrame {
    MenyAdmin adminMeny;
    private static InfDB idb;
    /**
     * Creates new form MainFrameAlien
     */
    public MainFrameAdmin(InfDB databas, String inloggadAdmin) {
        idb = databas;
        initComponents();
        // Fel uppstår här
        adminMeny = new MenyAdmin(idb, inloggadAdmin);
        pnlAdminMeny.setLayout(new BorderLayout());
        pnlAdminMeny.add(adminMeny);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdminMeny = new javax.swing.JPanel();
        pnlAdminHuvudPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout pnlAdminMenyLayout = new javax.swing.GroupLayout(pnlAdminMeny);
        pnlAdminMeny.setLayout(pnlAdminMenyLayout);
        pnlAdminMenyLayout.setHorizontalGroup(
            pnlAdminMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );
        pnlAdminMenyLayout.setVerticalGroup(
            pnlAdminMenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlAdminHuvudPanelLayout = new javax.swing.GroupLayout(pnlAdminHuvudPanel);
        pnlAdminHuvudPanel.setLayout(pnlAdminHuvudPanelLayout);
        pnlAdminHuvudPanelLayout.setHorizontalGroup(
            pnlAdminHuvudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );
        pnlAdminHuvudPanelLayout.setVerticalGroup(
            pnlAdminHuvudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlAdminMeny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAdminHuvudPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdminMeny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlAdminHuvudPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlAdminHuvudPanel;
    private javax.swing.JPanel pnlAdminMeny;
    // End of variables declaration//GEN-END:variables
}
