/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MIB;
 
import MIB.Inloggning.Inloggning;
import static MIB.Inloggning.Inloggning.getBehorighet;
import MIB.Inloggning.MenyAdmin;
import MIB.Inloggning.MenyAgent;
import MIB.Inloggning.MenyAlien;
import MIB.Inloggning.Sidor.AndraLosenord;
import MIB.Inloggning.Sidor.RegistreraAliens;
import MIB.Inloggning.Sidor.VisaChefForValtOmrade;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import oru.inf.InfDB;

/**
 *
 * @author Hampus
 */
public class MainFrameAgent extends javax.swing.JFrame {
    private static InfDB idb;
    public boolean inloggad = false;
    Inloggning inloggning;
    MenyAgent agentMeny;
    MenyAlien alienMeny;
    MenyAdmin adminMeny;
    AndraLosenord andraLosen;
    VisaChefForValtOmrade visaChef;
    RegistreraAliens regAliens;
    MainFrameAgent mainFrame;
    public int behorighet;
    /**
     * Creates new form MainFrame
     */
    public MainFrameAgent(InfDB databas) {
        idb = databas;
        initComponents();
        behorighet = MIB.Inloggning.Inloggning.getBehorighet();
        
        inloggning = new Inloggning(idb);
        agentMeny = new MenyAgent(idb);
        andraLosen = new AndraLosenord(idb, "");
        visaChef = new VisaChefForValtOmrade(idb);
        regAliens = new RegistreraAliens(idb);
        
        visaInnehallAgent();
      
        
        
    }
    

// Ska ändra innehåller i jlpHuvudPanel till AndraLosenord (JPanel)
    public void visaInnehallAgent(){
        
        jlpMenyVisaPanel.setLayout(new BorderLayout());
        jlpMenyVisaPanel.add(agentMeny, BorderLayout.NORTH);
    }
    
    public void visaInnehallAlien(){
        jlpMenyVisaPanel.setLayout(new BorderLayout());
        jlpMenyVisaPanel.add(alienMeny, BorderLayout.NORTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlpMenyVisaPanel = new javax.swing.JLayeredPane();
        jlpHuvudPanel = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));

        javax.swing.GroupLayout jlpMenyVisaPanelLayout = new javax.swing.GroupLayout(jlpMenyVisaPanel);
        jlpMenyVisaPanel.setLayout(jlpMenyVisaPanelLayout);
        jlpMenyVisaPanelLayout.setHorizontalGroup(
            jlpMenyVisaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 152, Short.MAX_VALUE)
        );
        jlpMenyVisaPanelLayout.setVerticalGroup(
            jlpMenyVisaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jlpHuvudPanelLayout = new javax.swing.GroupLayout(jlpHuvudPanel);
        jlpHuvudPanel.setLayout(jlpHuvudPanelLayout);
        jlpHuvudPanelLayout.setHorizontalGroup(
            jlpHuvudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );
        jlpHuvudPanelLayout.setVerticalGroup(
            jlpHuvudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jlpMenyVisaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlpHuvudPanel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlpMenyVisaPanel)
            .addComponent(jlpHuvudPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainFrameAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainFrameAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainFrameAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainFrameAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrameAgent().setVisible(true);
//            }
//        });
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jlpHuvudPanel;
    private javax.swing.JLayeredPane jlpMenyVisaPanel;
    // End of variables declaration//GEN-END:variables
}
